#
# Copyright 2020 Pejman Ghorbanzade. All rights reserved.
#

version: '3'
services:

  gio_webapp:
    build:
      context: .
      dockerfile: config/prod/Dockerfile
    image: docker.pkg.github.com/ghorbanzade/ghorbanzade.github.io/gio-webapp:latest
    ports:
      - 80:80
    restart: always
